CREATE TABLE CPI_DIRTY (
	COUNTRY TEXT NOT NULL,
	COUNTRY_CODE VARCHAR(3) NOT NULL,
	INDICATOR_NAME TEXT NOT NULL,
	INDICATOR_CODE TEXT NOT NULL,
	OBS_YEAR TEXT NOT NULL,
	INDICATOR_VALUE NUMERIC
);

DROP TABLE CPI_DIRTY;

SELECT
	*
FROM
	CPI_DIRTY